### PR TITLE
PCB review issues

### LINKED ISSUE #20: Naming switches
Follow the conversation over at [FC](https://github.com/nakujaproject/flight-control-computer/issues/13#issue-1120365114)

### PR DESCRIPTION
**Pull request by kimanimichael**
@0x6f736f646f Review.

### CODE REVIEW

**Comment by rodneyosodo** [comment]
@Mike-Kimani Please reference the issue you have implemented so that we can review the easily

**Comment by rodneyosodo** [comment]
Resolves #22

**Comment by rodneyosodo** [comment]
Resolves #19

**Comment by rodneyosodo** [comment]
Resolves #24

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Implement the issues that haven't been fixed

**Comment by rodneyosodo** [comment]
Resolves #10

**Comment by kimanimichael** [comment]
Resolves #15

**Comment by kimanimichael** [comment]
Resolves #12

**Comment by kimanimichael** [comment]
Resolves #27

**Comment by rodneyosodo** [comment]
Resolves #32

**Comment by rodneyosodo** [comment]
Resolves #16

**Comment by rodneyosodo** [comment]
Resolves #29

**Comment by kimanimichael** [comment]
Resolves #6

**Comment by rodneyosodo** [comment]
Resolves #31

**Comment by rodneyosodo** [comment]
Resolves #23

**Comment by rodneyosodo** [comment]
Resolves #21

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Requested minor changes

**Review by rodneyosodo — APPROVED** [review]

**Pull request merged**
