### PR TITLE
Fixing more issues.

### LINKED ISSUE #33: Redundancies in the sensors
- Pressure sensor
- IMU

### PR DESCRIPTION
**Pull request by kimanimichael**
Fixes 

#33 
#37 
#39 
#38 
#35 
#43 
#40 
#34 
#3

### CODE REVIEW

**Comment by rodneyosodo** [comment]
Why 4 layers?

**Comment by kimanimichael** [comment]
> Why 4 layers?

Why not?

**Comment by rodneyosodo** [comment]
It is more expensive

**Comment by kimanimichael** [comment]
> Why 4 layers?
I have a power layer and a ground layer.

**Pull request merged**
